/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.Jeu;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;


/**
 *
 * @author HKass
 */
public class VueGraphique extends javax.swing.JFrame implements Vue{

    /**
     * Creates new form VueGraphique
     */
    public VueGraphique() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            img_fc = ImageIO.read(new File("src/images/carte_face_cachee.png"));
            img_trefle = ImageIO.read(new File("src/images/trefle.png"));
            img_pique = ImageIO.read(new File("src/images/pique.png"));
            img_carreau = ImageIO.read(new File("src/images/carreau.png"));
            img_coeur = ImageIO.read(new File("src/images/coeur.png"));
            img_joker = ImageIO.read(new File("src/images/joker.png"));
        } catch (IOException ex) {
            Logger.getLogger(VueGraphique.class.getName()).log(Level.SEVERE, null, ex);
        }
        l_melange.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_c2 = new javax.swing.JPanel();
        p_c3 = new javax.swing.JPanel();
        p_c4 = new javax.swing.JPanel();
        p_c5 = new javax.swing.JPanel();
        p_c1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p_melange = new javax.swing.JPanel();
        l_melange = new javax.swing.JLabel();
        b_ajout = new javax.swing.JButton();
        b_lancer = new javax.swing.JButton();
        b_arret = new javax.swing.JButton();
        b_dist = new javax.swing.JButton();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        b_creer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        gagnant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        p_c2.setBackground(new java.awt.Color(51, 153, 255));
        p_c2.setForeground(new java.awt.Color(255, 255, 0));
        p_c2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout p_c2Layout = new javax.swing.GroupLayout(p_c2);
        p_c2.setLayout(p_c2Layout);
        p_c2Layout.setHorizontalGroup(
            p_c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        p_c2Layout.setVerticalGroup(
            p_c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        p_c3.setBackground(new java.awt.Color(51, 153, 255));
        p_c3.setForeground(new java.awt.Color(255, 255, 0));
        p_c3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout p_c3Layout = new javax.swing.GroupLayout(p_c3);
        p_c3.setLayout(p_c3Layout);
        p_c3Layout.setHorizontalGroup(
            p_c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        p_c3Layout.setVerticalGroup(
            p_c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        p_c4.setBackground(new java.awt.Color(51, 153, 255));
        p_c4.setForeground(new java.awt.Color(255, 255, 0));
        p_c4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout p_c4Layout = new javax.swing.GroupLayout(p_c4);
        p_c4.setLayout(p_c4Layout);
        p_c4Layout.setHorizontalGroup(
            p_c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        p_c4Layout.setVerticalGroup(
            p_c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        p_c5.setBackground(new java.awt.Color(51, 153, 255));
        p_c5.setForeground(new java.awt.Color(255, 255, 0));
        p_c5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout p_c5Layout = new javax.swing.GroupLayout(p_c5);
        p_c5.setLayout(p_c5Layout);
        p_c5Layout.setHorizontalGroup(
            p_c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        p_c5Layout.setVerticalGroup(
            p_c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        p_c1.setBackground(new java.awt.Color(51, 153, 255));
        p_c1.setForeground(new java.awt.Color(255, 255, 0));
        p_c1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout p_c1Layout = new javax.swing.GroupLayout(p_c1);
        p_c1.setLayout(p_c1Layout);
        p_c1Layout.setHorizontalGroup(
            p_c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        p_c1Layout.setVerticalGroup(
            p_c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        jLabel1.setText("J1:");

        jLabel2.setText("J2:");

        jLabel3.setText("J3:");

        jLabel4.setText("J5:");

        jLabel5.setText("J4:");

        l_melange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/melange_pti.gif"))); // NOI18N
        l_melange.setText(" ");

        javax.swing.GroupLayout p_melangeLayout = new javax.swing.GroupLayout(p_melange);
        p_melange.setLayout(p_melangeLayout);
        p_melangeLayout.setHorizontalGroup(
            p_melangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_melangeLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(l_melange)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        p_melangeLayout.setVerticalGroup(
            p_melangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_melangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_melange, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        b_ajout.setText("Ajouter Joueurs");

        b_lancer.setText("Lancer");

        b_arret.setText("Arreter");

        b_dist.setText("Distribuer");

        j1.setText(" ");

        j2.setText(" ");

        j3.setText(" ");

        j4.setText(" ");

        j5.setText(" ");

        b_creer.setText("Créer jeu");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Le gagant est :");

        gagnant.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gagnant.setForeground(new java.awt.Color(255, 0, 0));
        gagnant.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(p_c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_creer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_ajout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_dist, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_lancer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_arret, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gagnant, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(p_melange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(p_melange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(j1)
                    .addComponent(j2)
                    .addComponent(j3)
                    .addComponent(j4)
                    .addComponent(j5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gagnant))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ajout)
                    .addComponent(b_lancer)
                    .addComponent(b_arret)
                    .addComponent(b_dist)
                    .addComponent(b_creer))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGraphique().setVisible(true);
            }
        });
    }
    
    @Override
    public void faireUnTruc() {
        
    }

    @Override
    public void setControlleur(Jeu jeu) {
        this.jeu = jeu;
    }

    @Override
    public void demandeNomJoueur() {
        String nom = (String) JOptionPane.showInputDialog(p_melange, 
                "Entrez le nom du joueur (vide pour terminer)", "Ajout de joueur", 
                JOptionPane.PLAIN_MESSAGE, null, null, ""); 
        if(nom==null || nom.isEmpty()) {
            int termine = JOptionPane.showConfirmDialog(p_melange, 
                    "Vous confirmez terminer l'ajout?", 
                    "Ajout de joueur", JOptionPane.YES_NO_OPTION); 
            if(termine==JOptionPane.YES_OPTION) jeu.entreeJoueursTerminee();
        }
        else jeu.ajouterJoueur(nom);
    }

    @Override
    public void demandeRetourner() {
        JOptionPane.showMessageDialog(p_melange, "Tapez OK pour retourner les cartes", 
                "Retournement des cartes", JOptionPane.INFORMATION_MESSAGE); 
    }

    @Override
    public void demandeNewJeu() {
        int continuer = JOptionPane.showConfirmDialog(p_melange, 
                    "Voulez-vous continuez un nouveau tour ?", 
                    "Nouveau tour", JOptionPane.YES_NO_OPTION); 
        if(continuer==JOptionPane.NO_OPTION) jeu.arreter();
    }

    @Override
    public void afficherGagnant(String nom) {
        gagnant.setText(nom);
    }

    @Override
    public void afficherNomJoueur(int pos, String nom) {
        switch(pos) {
            case 1: j1.setText(nom); break;
            case 2: j2.setText(nom); break;
            case 3: j3.setText(nom); break;
            case 4: j4.setText(nom); break;
            case 5: j5.setText(nom); break;
        }
    }

    @Override
    public void afficherFaceCacheCarteJoueur(int i, String nom) {
        Graphics g; 
        switch(i) {
            case 1: g = p_c1.getGraphics(); break;
            case 2: g = p_c2.getGraphics(); break;
            case 3: g = p_c3.getGraphics(); break;
            case 4: g = p_c4.getGraphics(); break;
            case 5: g = p_c5.getGraphics(); break;
            default: g = p_c1.getGraphics(); break;
        }
        g.drawImage(img_fc, 0, 0, 100, 159, null);
    }

    @Override
    public void afficherCarteJoueur(int i, String nom, String val, String type) {
        Graphics g; 
        switch(i) {
            case 1: g = p_c1.getGraphics(); break;
            case 2: g = p_c2.getGraphics(); break;
            case 3: g = p_c3.getGraphics(); break;
            case 4: g = p_c4.getGraphics(); break;
            case 5: g = p_c5.getGraphics(); break;
            default: g = p_c1.getGraphics(); break;
        }
        switch (type) {
            case "TREFLE":
                g.drawImage(img_trefle, 0, 0, 100, 159, this);
                break;
            case "PIQUE":
                g.drawImage(img_pique, 0, 0, 100, 159, this);
                break;
            case "CARREAU":
                g.drawImage(img_carreau, 0, 0, 100, 159, this);
                break;
            case "COEUR":
                g.drawImage(img_coeur, 0, 0, 100, 159, this);
                break;
            default:
                g.drawImage(img_joker, 0, 0, 100, 159, this);
                break;
        }
        g.setColor(Color.yellow);
        g.drawString(val, 10, 80);
    }

    @Override
    public void effetMelange() {
        l_melange.setVisible(true);
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {}
        l_melange.setVisible(false);
    }
    
    Jeu jeu;
    BufferedImage img_fc;
    BufferedImage img_coeur;
    BufferedImage img_carreau;
    BufferedImage img_pique;
    BufferedImage img_trefle;
    BufferedImage img_joker;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_ajout;
    private javax.swing.JButton b_arret;
    private javax.swing.JButton b_creer;
    private javax.swing.JButton b_dist;
    private javax.swing.JButton b_lancer;
    private javax.swing.JLabel gagnant;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_melange;
    private javax.swing.JPanel p_c1;
    private javax.swing.JPanel p_c2;
    private javax.swing.JPanel p_c3;
    private javax.swing.JPanel p_c4;
    private javax.swing.JPanel p_c5;
    private javax.swing.JPanel p_melange;
    // End of variables declaration//GEN-END:variables

}
